services:
  db:
    image: postgres:13.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
  phx:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/dayhist
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}