services:
  db:
    image: postgres:13.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
  phx:
    build: ./phx
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 80:80